---

- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: userPasswd
      prompt: "Enter your password: "

  tasks:
    - name: apt dependencies
      apt: name={{ item }} state=present
      with_items:
        - exuberant-ctags 
        - git
        - golang-go
        - neovim 
        - nodejs 
        - npm 
        - openjdk-8-jdk,
        - python3-gi
        - python3-pip 
        - python3-xlib
        - ripgrep 
        - xsel
        - yarn 
        - zsh

    - name: Pip dependencies
      pip: name={{ item }} state=present
      with_items:
        - jedi
        - virtualenv

    - name: Install pygrid
      command: /home/{{ userName }}/.config/dotfiles/pygrid.sh {{ userName }}

    - name: Activate zshell
      expect:
        command: chsh -s /bin/zsh
        responses:
          'Password: ': "{{ userPasswd }}"

    - name: Install oh-my-zsh
      shell: |
        cd
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        rm .zshrc
        mv .zshrc.pre-oh-my-zsh .zshrc

    - name: Install powerline fonts
      shell: |
        mkdir -p ~/repos/notMine 
        cd ~/repos/notMine
        git clone https://github.com/powerline/fonts.git --depth=1
        . fonts/install.sh
        rm -rf fonts

    - name: Clone fzf
      shell: |
        cd ~/bin
        git clone --depth 1 https://github.com/junegunn/fzf.git fzf
        cd fzf

    - name: Install fzf
      expect:
        command: ./install
        responses:
          'Do you want to enable fuzzy auto-completion? ([y]/n)': 'n'
          'Do you want to enable key bindings? ([y]/n)': 'n'
          'Do you want to update your shell configuration files? ([y]/n)': 'n'

    - name: Remove fzf junk
      shell: rm ~/.fzf.*

    - name: Install neovim
      shell: |
        mkdir -p ~/.config/nvim/autoload
        curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

        cd ~/.config/nvim
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        deactivate

        vim -c "PlugInstall" -c "qa\!"
        vim -c "GoInstallBinaries" -c "qa\!"
