---

- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: userPasswd
      prompt: "Enter your password: "

  tasks:
    - name: apt dependencies
      apt: name={{ item }} state=present
      with_items:
        - exuberant-ctags 
        - git
        - golang-go
        - neovim 
        - nodejs 
        - npm 
        - openjdk-8-jdk,
        - python3-gi
        - python3-pip 
        - python3-xlib
        - ripgrep 
        - xsel
        - yarn 
        - zsh

    - name: Pip dependencies
      pip: name={{ item }} state=present
      with_items:
        - jedi
        - virtualenv

    - name: Install pygrid
      command: /home/{{ userName }}/.config/dotfiles/pygrid.sh {{ userName }}

    - name: Activate zshell
      expect:
        command: chsh -s /bin/zsh
        responses:
          'Password: ': "{{ userPasswd }}"

    - name: Install oh-my-zsh
      command: /home/{{ userName }}/.config/dotfiles/ohMyZsh.sh {{ userName }}

    - name: Install powerline fonts
      command: /home/{{ userName }}/.config/dotfiles/powerline.sh {{ userName }}

    - name: Install fzf
      expect:
        command: /home/{{ userName }}/.config/dotfiles/fzf.sh {{ userName }}
        responses:
          '*': 'n'

    - name: Install neovim
      command: /home/{{ userName }}/.config/dotfiles/neovim.sh {{ userName }}

    - name: Configure nvim plugins
      command: bash -c $(nvim -c "PlugInstall" -c "qa\!")

    - name: Install golang binaries
      command: bash -c $(nvim -c "GoInstallBinaries" -c "qa\!")
